import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "../components/theme-provider";

const inter = Inter({ subsets: ["latin"] });
import Sidebar from "@/components/ui/sidebar/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head></head>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div>
            {/* <h1>Mode Toggle</h1> */}
            {/* <ModeToggle /> */}
          </div>
          <div className="flex h-screen  ">
            <div className="hidden sm:block bg-sidebar flex-none w-1/7">
              <Sidebar />
            </div>

            <div className="flex-grow bg-red-500 ">
              {/* Children section content goes here */}
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
